config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  # root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  authenticate :admin do
    get '/admins', to: 'admins#index'
    resources :courses, except: [:show]
    resources :categories, except: [:show]
    resources :daily_menus, except: [:show]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
        #  :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :courses

  validates :name, presence: true
  before_destroy :check_courses

  private

  def check_courses
    raise 'You cannot destroy this Category as there are courses existing in it' if self.courses.present?
  end

end

app/models/course.rb
class Course < ApplicationRecord
  scope :measurement_based, -> { where(type: 'MeasurementBased') }
  scope :portion_based, -> { where(type: 'PortionBased') }

  has_and_belongs_to_many :daily_menus
  has_one :measurement, dependent: :destroy
  has_many :pricings, dependent: :destroy
  belongs_to :category

  accepts_nested_attributes_for :measurement, reject_if: :all_blank

  validates :name, presence: true
  validates_associated :measurement
  validates_presence_of :measurement
  # validates :price_ratio, presence: true

  before_destroy :check_for_menu

  private

  def check_for_menu
    raise 'You cannot destroy this Course as it is included in a daily menu' if self.daily_menus.present?
  end

end

app/models/daily_menu.rb
class DailyMenu < ApplicationRecord
  has_and_belongs_to_many :courses
  has_many :pricings, dependent: :destroy

  validates :date, presence: true, uniqueness: true
  accepts_nested_attributes_for :pricings, reject_if: :all_blank

  private


end

app/models/measurement.rb
class Measurement < ApplicationRecord
  belongs_to :course

  validates_presence_of :unit, :quantity, :name
end

app/models/measurement_based.rb
class MeasurementBased < Course
  # validates :weight_ratio, presence: true
  # validates :weight, presence: true

  # before_save :calculate_final_price

  private

  # def calculate_final_price
  #   self.final_price = self.weight * (self.price_ratio / self.weight_ratio)
  # end

end

app/models/portion_based.rb
class PortionBased < Course
  # validates :portion_ratio, presence: true
  # validates :portion, presence: true

  # before_save :calculate_final_price

  private

  # def calculate_final_price
  #   self.final_price = self.portion * (self.price_ratio / self.portion_ratio)
  # end

end

app/models/pricing.rb
class Pricing < ApplicationRecord
  belongs_to :course
  belongs_to :daily_menu

  validates :final_price, presence: true

  private

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.includes(:courses).all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      redirect_to new_category_path, flash: { alert: @category.errors.full_messages.join(', ') }
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to categories_path
    else
      redirect_to edit_category_path, flash: { alert: @category.errors.full_messages.join(', ') }
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  rescue_from 'Category::StandardError' do |exception|
    redirect_to categories_path, alert: exception.message
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end


end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  def index
    @courses = Course.includes(:category, :measurement).all
  end

  def new
    @course = Course.new
    @course.build_measurement
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to courses_path
    else
      redirect_to new_course_path, flash: { alert: @course.errors.full_messages.join(', ') }
    end
  end

  def edit
    # @course.build_measurement if @course.build_measurement.nil?
  end

  def update
    if @course.update(course_params)
      redirect_to courses_path
    else
      redirect_to edit_course_path, flash: { alert: @course.errors.full_messages.join(', ') }
    end
  end

  def destroy
    @course.destroy
    redirect_to courses_path
  end

  rescue_from 'Course::StandardError' do |exception|
    redirect_to courses_path, alert: exception.message
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    if params.has_key? :measurement_based
      params[:course] = params.delete :measurement_based
    elsif params.has_key? :portion_based
      params[:course] = params.delete :portion_based
    end
    params.require(:course).permit(:type, :name, :description, :weight, :category_id, :daily_menu_id, measurement_attributes: [:name, :unit, :quantity])
  end

end

app/controllers/daily_menus_controller.rb
class DailyMenusController < ApplicationController

  before_action :set_daily_menu, only: [:edit, :update, :destroy]
  before_action :set_categories, only: [:new, :create, :edit]

  def index
    @daily_menus = DailyMenu.includes(:courses, {courses: :category}).all
  end

  def new
    @daily_menu = DailyMenu.new
    @daily_menu.pricings.build
  end

  def create
    @daily_menu = DailyMenu.new(daily_menu_params)
    if @daily_menu.save
      redirect_to daily_menus_path
    else
      redirect_to new_daily_menu_path, flash: { alert: @daily_menu.errors.full_messages.join(', ') }
    end
  end

  def edit; end

  def update
    if @daily_menu.update(daily_menu_params)
      redirect_to daily_menus_path
    else
      redirect_to edit_daily_menu_path, flash: { alert: @daily_menu.errors.full_messages.join(', ') }
    end
  end

  def destroy
    @daily_menu.destroy
    redirect_to daily_menus_path
  end


  private

  def set_categories
    @categories = Category.includes(:courses,{courses: :measurement}).all
  end

  def set_daily_menu
    @daily_menu = DailyMenu.find(params[:id])
  end

  def daily_menu_params
    params.require(:daily_menu).permit(:date, :price, course_ids: [], pricings_attributes: [:final_price, :course_id])
  end
  
end

app/helpers/admins_helper.rb
module AdminsHelper
  def no_categories
    Category.all.empty?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/daily_menus_helper.rb
module DailyMenusHelper
end

app/views/admins/index.erb
<h2>Hello Admin!</h2>

<div class='container-fluid'>

  <div class='row'>
    <div class='col-4'>
      <div>Manage categories</div>
      <%= link_to 'Create a category', new_category_path %>
      <%= link_to 'View categories', categories_path %>
    </div>
    <div class='col-4'>
      <div>Manage courses</div>
      <% if no_categories %>
        Please create a category first
      <% end %>
      <% unless no_categories %>
        <%= link_to 'Create a course', new_course_path %>
        <%= link_to 'View courses', courses_path %>
      <% end %>
    </div>

    <div class='col-4'>
      <div>Manage daily menu</div>
      <%= link_to 'Create a daily menu', new_daily_menu_path %>
      <%= link_to 'View all daily menus', daily_menus_path %>
    </div>
  </div>

</div>

app/views/categories/_form_content.erb
<div class='form-group'>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<%= f.submit 'Save', class: 'btn btn-primary' %>

app/views/categories/edit.erb
<h3> Edit a Category </h3>

<%= form_with model: @category, url: category_path, method: :patch do |f| %>
  <%= render 'form_content', f: f %>
<% end %>

app/views/categories/index.erb
<div class='p-3'>
  <%= link_to 'New category', new_category_path, class: 'btn btn-outline-primary' %>
</div>
<div class='container-fluid'>
  <div class='row'>
    <% @categories.each do |category| %>

      <div class='card col-4'>
        <div class='card-body'>
          <h5 class='card-title'><%= category.name %></h5>
          <div class='card-text'>
            <p>Courses: <%= category.courses.map{ |x| x.name}.join(", ") %> </p>
            <%= link_to 'Edit category', edit_category_path(category) %>
            <%= link_to 'Delete category', category_path(category), method: :delete %>
          </div>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/categories/new.erb
<h3> Create a New Category </h3>


<%= form_with model: @category, url: categories_path do |f| %>
  <%= render 'form_content', f: f %>
<% end %>

app/views/courses/_form_content.erb
<div class='form-group'>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class='form-group'>
  <%= f.label :description %>
  <%= f.text_field :description, class: 'form-control' %>
</div>

<div class='form-group'>
  <%= f.label :category, value: 'Choose a category for the course' %>
  <%= f.select(:category_id, Category.all.collect { |c| [c.name, c.id] }, {}, {class: 'form-control'}) %>
</div>

<%= f.fields_for :measurement do |ff| %>
  <div class='form-group'>
    <%= ff.label :name, 'Describe the measurement system (e.g. Weight, volume, etc.)' %>
    <%= ff.text_field :name, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= ff.label :unit, 'Describe the unit of measurement (e.g. g, mL, kg)' %>
    <%= ff.text_field :unit, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= ff.label :quantity, 'Quantity (in the above specified unit of measure)' %>
    <%= ff.number_field :quantity, class: 'form-control' %>
  </div>
<% end %>

<div class='form-group'>
  <%= f.label :type %>
  <%= f.select(:type, [['Measurement-based', 'MeasurementBased'], ['Portion-based', 'PortionBased']], {}, {class: 'form-control type-dropdown'}) %>
</div>



<%# <div class='form-group weight-group'> 
  <%= f.label :weight, value: 'Weight in grams' 
  <%= f.number_field :weight, class: 'form-control' 
</div> %>

<%# <div class='form-group portion-group d-none'>
  <%= f.label :portion 
  <%= f.number_field :portion, class: 'form-control' 
</div>

<div class='form-group weight-group'>
  <%= f.label :weight_ratio, value: 'Weight Ratio (in grams)' 
  <p class='font-weight-light'> Create a ratio to calculate the final cost. Define the weight part of the ratio here and the price part below (e.g. 10 g here and $20 below for a ratio of 10:20 or $2/g)<p>
  <%= f.number_field :weight_ratio, class: 'form-control' 
</div>

<div class='form-group portion-group d-none'>
  <%= f.label :portion_ratio 
  <p class='font-weight-light'> Create a ratio to calculate the final cost. Define the portion part of the ratio here and the price part below (e.g. 10 portions here and $20 below for a ratio of 10:20 or $2/portion) <p>
  <%= f.number_field :portion_ratio, class: 'form-control' 
</div>

<div class='form-group'>
  <%= f.label :price_ratio 
  <p class='font-weight-light'> Set how much money it costs for the above defined weight/portion (in $) <p>
  <%= f.number_field :price_ratio, class: 'form-control' 
</div> %>

<%= f.submit 'Save', class: 'btn btn-primary' %>

app/views/courses/edit.erb
<h3> Edit a Course </h3>

<%= form_with model: @course, url: course_path, method: :patch do |f| %>
  <%= render 'form_content', f: f %>
<% end %>

app/views/courses/index.erb
<div class='p-3'>
  <%= link_to 'New Course', new_course_path, class: 'btn btn-outline-primary' %>
</div>
<div class='container-fluid'>
  <div class='row'>
    <% @courses.each do |course| %>

      <div class='card col-4'>
        <div class='card-body'>
          <h5 class='card-title'><%= course.name %></h5>
          <div class='card-text'>
            <p>Description: <%= course.description %> </p>
            <p>Category: <%= course.category.name %> </p>
            <% if course.measurement.present? %>
              <p>Quantity: <%= course.measurement.quantity %> <%= course.measurement.unit %> </p>
            <% end %>
            <%= link_to 'Edit course', edit_course_path(course) %>
            <%= link_to 'Delete course', course_path(course), method: :delete %>
          </div>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/courses/new.erb
<h3> Create a New Course </h3>


<%= form_with model: @course, url: courses_path do |f| %>
  <%= render 'form_content', f: f %>
<% end %>

app/views/daily_menus/_form_content.erb
<div class='form-group'>
  <%= f.label :date, value: 'Date' %>
  <p class='font-weight-lighter'>Please input date in YYYY-MM-DD format (e.g. 2020-07-22). You can only have one daily menu per day.</p>
  <%= f.text_field :date, class: '', id: 'datepicker' %>
</div>

<div class='form-group'>
  <%= f.label :category, value: 'Choose a category for the course. You are not required to choose a course for every single category.' %>

  <div class='card my-2'>
    <% @categories.each do |category| %>
      <p><%= category.name %></p>
      <% klass = f.object.class.model_name.param_key %>
      <%= f.select :course_ids, options_for_select(category.courses.map {|c| [c.name, c.id, {'data-price' => c.final_price, 'data-unit' => c.measurement.unit, 'data-measurement' => c.measurement.name, 'data-quantity' => c.measurement.quantity }]}), {include_blank: true}, {class: "daily-menu-courses-dropdown", 'data-category-id' => category.id, name: "#{klass}[course_ids][]"} %>

      <div class='mb-3'> Quantity: <span id="dropdown-<%= category.id %>" class='suggested-prices'> </span> </div>

      <div class='mb-3'>
        <%= f.fields_for :pricings do |ff| %>
          <div class='form-group'>
            <%= ff.label :final_price, 'Input the price with the quantity above in mind' %>
            <%= ff.number_field :final_price, step: :any, class: 'form-control' %>
            <%= ff.hidden_field :course_id, class: "pricing-course-#{category.id}" %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

</div>

<%# <div class='form-group'>
  <%= f.label :price, value: 'Suggested price is calculated from the sum of the prices of the above courses' 
  <%= f.number_field :price, class: 'form-control', id: 'daily-menu-price-field' 
</div> %>

<%= f.submit 'Save', class: 'btn btn-primary' %>

app/views/daily_menus/edit.erb
<h3> Edit a Daily Menu </h3>

<%= form_with model: @daily_menu, url: daily_menu_path, method: :patch do |f| %>
  <%= render 'form_content', f: f %>
<% end %>

app/views/daily_menus/index.erb
<div class='p-3'>
  <%= link_to 'New Daily Menu', new_daily_menu_path, class: 'btn btn-outline-primary' %>
</div>
<div class='container-fluid'>
  <div class='row'>
    <% @daily_menus.each do |daily_menu| %>

      <div class='card col-4'>
        <div class='card-body'>
          <h5 class='card-title'><%= daily_menu.date %></h5>
          <div class='card-text'>
            <div class='mb-3'>Courses:</div>
            <% daily_menu.courses.each do |course| %>
              <div class='border rounded p-3 mb-3'>
                <p><%= course.name %> - <%= course.category.name %></p>
                <p>Price: $<%= daily_menu.pricings.find_by(course: course).final_price %> / 
                  <% if course.type == 'PortionBased' %>
                    1 Portion
                  <% else %>
                    <%= course.measurement.quantity%> <%= course.measurement.unit%> 
                  <% end %>
                 </p>
              </div>
            <% end %>
            <%= link_to 'Edit daily_menu', edit_daily_menu_path(daily_menu) %>
            <%= link_to 'Delete daily_menu', daily_menu_path(daily_menu), method: :delete %>
          </div>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/daily_menus/new.erb
<h3> Create a New Daily Menu </h3>


<%= form_with model: @daily_menu, url: daily_menus_path do |f| %>
  <%= render 'form_content', f: f %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LunchProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body>

    <%= yield %>
    <% if current_admin %>
      <%= link_to 'Back to admin dashboard', admins_path, class: 'btn btn-outline-primary mt-5 mx-3' %>
    <% end %>
    <p class="notice"><%= notice %></p>
    <% if flash[:alert] %>
      <div class="alert text-danger"><%= flash[:alert] %></div>
    <% end %>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>